### ISSUE TITLE
cashflow report error

### ISSUE THREAD

**Issue by michaelachrisco** [6twenty/cashflow#2]
Giving this a shot for loading transactional data from .ofx file. 
Seems to not like this block:
```ruby
    def group_transactions_by_month_and_type(by_month, transactions)
      transactions.each do |transaction|
        this, year, month = Date.today, transaction.date.year, transaction.date.month
        type = "#{transaction.transaction_type}s".to_sym # pluralize by appending "s"
        key  = "#{year}-#{month}"
        key  = :current if year == this.year && month == this.month
        by_month[key][type] << transaction
      end

      by_month
    end
```

```bash
michael@ubuntu:~\ $ cashflow load ~/Downloads/export.ofx 
Successfully loaded the transactions for 999999=9
michael@ubuntu:~\ $ cashflow report
/home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/report.rb:96:in `block in group_transactions_by_month_and_type': undefined method `<<' for nil:NilClass (NoMethodError)
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/report.rb:91:in `each'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/report.rb:91:in `group_transactions_by_month_and_type'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/report.rb:31:in `initialize'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/cli.rb:24:in `new'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/lib/cashflow/cli.rb:24:in `report'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/gems/cashflow-0.1.4/bin/cashflow:15:in `<top (required)>'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/bin/cashflow:23:in `load'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/bin/cashflow:23:in `<main>'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
        from /home/michael/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by michaelachrisco** [comment]
Issue is not with the gem, the financial institution did not include dates on any of the transactions. Closing.
